### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by RobinHirst11** [KafetzisThomas/SafeArchive#17]
##  Request: Linux .deb Support 

**As a Linux user, I'm excited about this project!**  I'm especially interested in using it on my Chromebook, which relies on Debian-based Linux. 

**However, I'm currently unable to use it because the project doesn't offer .deb packages.**  

**Could you please consider adding .deb packages to the Linux download options?** This would significantly expand the project's reach and allow many more Linux users, including Chromebook users, to benefit from it. 

**Adding .deb support would be a fantastic improvement!** It would make the project even more inclusive and user-friendly. 

**I'd also be open to exploring other package formats, such as AppImage, to further broaden the project's accessibility.** Providing clear installation instructions for different Linux distributions would also be very helpful.

**Thank you for considering this request!**

**Comment by KafetzisThomas** [comment]
Hey there,

Thank you so much for your interest in SafeArchive and for your thoughtful suggestion! I'm thrilled to hear that you're excited about using the project on your Chromebook and other Debian-based Linux systems.

Currently, the build process allows users to create packages easily by running a single command for `Windows`, `Debian`, and `RPM-based` distributions. Packaging the program yourself will create an **AppImage** format, which is a convenient and portable option for many users.

 While I understand the convenience of pre-built .deb packages, offering multiple packages for each release would significantly increase the time spent on packaging, diverting efforts from core development.

However, packaging the program yourself has its benefits, such as understanding the build process and ensuring that antivirus software isn't triggered, fostering greater trust in the open-source community. For detailed instructions on packaging, please refer to the [documentation](https://github.com/KafetzisThomas/SafeArchive/blob/main/docs/package_program.md).
